/* eslint-disable eqeqeq */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
import jwt from 'jsonwebtoken';
import Wallet from '../models/Wallet';
import User from '../models/User';
import elastic from '../helpers/elasticsearch';
import responses from '../utils/responses';
import DataProtector from '../utils/dataProtector';
import traceLogger from '../logger/traceLogger';
import ConnectionController from './ConnectionController';
import SettingController from './SettingController';
import config from '../config';
import notification from '../utils/notification';